export const TRIGGER_NAV = "TRIGGER_NAV"
export const TRIGGER_ASIDE = "TRIGGER_ASIDE"
export const ASIDE_NAV = "ASIDE_NAV"
export const DESKTOP = "DESKTOP"
export const MOBILE = "MOBILE"
export const ACTIVE_SECTION = "ACTIVE_SECTION"
